--- frozen-bubble-1.0.0/Makefile~	2004-09-30 15:28:42.000000000 +0000
+++ frozen-bubble-1.0.0/Makefile	2004-09-30 15:29:11.000000000 +0000
@@ -8,8 +8,8 @@
 all: dirs
 
 dirs:
-	@if ! perl -e 'use SDL'; then echo -e "\n    *** I need perl-SDL installed"; false; fi
-	@if ! perl -e 'use SDL; ($$mj, $$mn, $$mc) = split /\./, $$SDL::VERSION; exit 1 if $$mj<1 || $$mn<19'; then echo -e "\n    *** I need perl-SDL version 1.19.0 or upper"; false; fi
+	#@if ! perl -e 'use SDL'; then echo -e "\n    *** I need perl-SDL installed"; false; fi
+	#@if ! perl -e 'use SDL; ($$mj, $$mn, $$mc) = split /\./, $$SDL::VERSION; exit 1 if $$mj<1 || $$mn<19'; then echo -e "\n    *** I need perl-SDL version 1.19.0 or upper"; false; fi
 	@for n in . $(DIRS); do \
 		[ "$$n" = "." ] || $(MAKE) -C $$n ;\
 	done
