--- sysvinit-2.85/src/Makefile~	2001-11-06 11:58:16.000000000 +0000
+++ sysvinit-2.85/src/Makefile	2004-10-14 14:44:20.000000000 +0000
@@ -8,7 +8,7 @@
 # Version:	@(#)Makefile  2.83-3  06-Nov-2001  miquels@cistron.nl
 #
 
-CC	= cc
+
 CFLAGS	= -Wall -O2 -D_GNU_SOURCE
 LDFLAGS	= -s
 STATIC	=
@@ -24,13 +24,11 @@
 BIN_OWNER	= root
 BIN_GROUP	= root
 BIN_COMBO	= $(BIN_OWNER).$(BIN_GROUP)
-INSTALL		= install -o $(BIN_OWNER) -g $(BIN_GROUP)
+INSTALL		= install
 MANDIR		= /usr/share/man
 
 # Additional libs for Gnu Libc
-ifneq ($(wildcard /usr/lib/libcrypt.a),)
 LCRYPT		= -lcrypt
-endif
 
 all:		$(PROGS)
 
@@ -88,28 +86,10 @@
 		$(INSTALL) -m 755 halt init killall5 sulogin \
 			runlevel shutdown $(ROOT)/sbin
 		# These are not installed by default
-ifeq ($(DEBIAN),)
 		$(INSTALL) -m 555 utmpdump wall $(ROOT)/usr/bin
-endif
-		# $(INSTALL) -m 755 etc/initscript.sample $(ROOT)/etc
-		$(INSTALL) -m 755 mesg last $(ROOT)/usr/bin
-		cd $(ROOT)/sbin; ln -sf halt reboot; chown $(BIN_COMBO) reboot
-		cd $(ROOT)/sbin; ln -sf halt poweroff; chown $(BIN_COMBO) poweroff
-		cd $(ROOT)/sbin; ln -sf init telinit; chown $(BIN_COMBO) telinit
-		cd $(ROOT)/bin; ln -sf ../sbin/killall5 pidof; chown $(BIN_COMBO) pidof
-		cd $(ROOT)/usr/bin; ln -sf last lastb; chown $(BIN_COMBO) lastb
-		$(INSTALL) -m 644 initreq.h $(ROOT)/usr/include
-		$(INSTALL) -m 644 ../man/*.8 $(ROOT)$(MANDIR)/man8
-		$(INSTALL) -m 644 ../man/*.5 $(ROOT)$(MANDIR)/man5
-ifeq ($(DEBIAN),)
-		$(INSTALL) -m 644 ../man/wall.1 $(ROOT)$(MANDIR)/man1
-endif
-		$(INSTALL) -m 644 ../man/last.1 ../man/lastb.1 ../man/mesg.1 \
-			$(ROOT)$(MANDIR)/man1
-		#
-		# This part is skipped on debian systems, the
-		# debian.preinst script takes care of it.
-		@if [ ! -p /dev/initctl ]; then \
-		 echo "Creating /dev/initctl"; \
-		 rm -f /dev/initctl; \
-		 mknod -m 600 /dev/initctl p; fi
+		$(INSTALL) -m 755 mesg last     $(ROOT)/usr/bin
+		cd $(ROOT)/sbin; ln -sf halt reboot
+		cd $(ROOT)/sbin; ln -sf halt poweroff
+		cd $(ROOT)/sbin; ln -sf init telinit
+		cd $(ROOT)/bin; ln -sf ../sbin/killall5 pidof
+		cd $(ROOT)/usr/bin; ln -sf last lastb
