diff -Nur initscripts-6.40-1/src/Makefile initscripts-6.40-1-patched/src/Makefile
--- initscripts-6.40-1/src/Makefile	2001-12-13 08:38:03.000000000 +0000
+++ initscripts-6.40-1-patched/src/Makefile	2004-01-22 18:52:45.000000000 +0000
@@ -1,5 +1,5 @@
-CC = arm-linux-gcc
-CFLAGS+=$(RPM_OPT_FLAGS) -Wall -D_GNU_SOURCE -march=armv4 -mtune=strongarm1100 -mshort-load-bytes -g
+#CC = arm-linux-gcc
+#CFLAGS+=-Wall -D_GNU_SOURCE -march=armv4 -mtune=strongarm1100 -mshort-load-bytes -g
 
 PROGS=usernetctl doexec netreport testd usleep ipcalc initlog minilogd \
 	getkey ppp-watch consoletype
@@ -47,16 +47,16 @@
 	install -m 755 testdinit $(ROOT)/etc/init.d/testd
 
 ipcalc: ipcalc.o
-	$(CC) $(LDFLAGS) -o $@ $< ../../popt-1.4/.libs/libpopt.a
+	$(CC) $(LDFLAGS) -o $@ $< -lpopt
 
 initlog: $(INITLOG_OBJS)
-	$(CC) $(LDFLAGS) -o $@ $(INITLOG_OBJS) ../../popt-1.4/.libs/libpopt.a
+	$(CC) $(LDFLAGS) -o $@ $(INITLOG_OBJS) -lpopt
 
 usleep: $(USLEEP_OBJS)
-	$(CC) $(LDFLAGS) -o $@ $(USLEEP_OBJS) ../../popt-1.4/.libs/libpopt.a
+	$(CC) $(LDFLAGS) -o $@ $(USLEEP_OBJS) -lpopt
 
 ppp-watch: $(PPPWATCH_OBJS)
-	$(CC) $(LDFLAGS) -o $@ $(PPPWATCH_OBJS) ../../popt-1.4/.libs/libglib.a
+	$(CC) $(LDFLAGS) -o $@ $(PPPWATCH_OBJS) -lpopt
 shvar.o: shvar.c
 	$(CC) $(CFLAGS) `glib-config --cflags` -c shvar.c -o shvar.o
 ppp-watch.o: ppp-watch.c
