#!/bin/ash

# Set the path.
PATH=/sbin:/bin

# Kill all processes
#/sbin/killall -15
killall -15
sleep 3
#/sbin/killall -9
killall -9

# If they want to run something in single user mode, might as well run it...
for I in /etc/rc1.d/S[0-9][0-9]*; do
	# Check if the scripts is there.
	[ ! -f $I ] && continue
	[ ! -x $I ] && continue

	[ "$I" = "/etc/rc1.d/S00single" ] && continue
	$I start
done

# Now go to the single user level.
echo $"Telling INIT to go to single user mode."
exec init -t1 S

