#!/bin/sh

for app in firefox mozilla skipstone dillo helpviewer konqueror amaya; do
  if [ -x "`which $app`" ]; then 
    exec "$app" "$@"
    exit 0
  fi
done

for app in w3m lynx links vim vi; do
  if [ -x "`which $app`" ]; then 
    exec xterm -e "$app" "$@"
    exit 0
  fi
done

echo "Can't find any web browser installed... last try..." >&2

exec netscape "$@"
