#!/bin/sh
#
# X11 ROM apm wrapper
# http://www.pdaXrom.org
#

APM=/usr/bin/apm.x

if [ "$1" = "--suspend" -o "$1" = "-s" -o "$1" = "--su" ]; then
    STATUS=`cardctl status | grep '\[ready\]'`
    if [ "X$STATUS" != "X" ]; then
        cardctl eject 2>/dev/null
	#if pidof dhcpcd >/dev/null; then
	#    kill `pidof dhcpcd`
	#fi
	sleep 1
	$APM --suspend
        cardctl insert 2>/dev/null
    else
	$APM --suspend
    fi
else
    $APM $@
fi
