--- nvpanel/Nvpanel/Makefile~	2005-01-07 13:30:30.000000000 +0000
+++ nvpanel/Nvpanel/Makefile	2005-01-07 13:30:46.000000000 +0000
@@ -22,7 +22,7 @@
 $(error Could not determine gtk LDFLAGS)
 endif
 CFLAGS = -g -Wall $(GTK_CFLAGS)
-LDFLAGS = $(GTK_LDFLAGS) -L../commonlib -lcommonlib
+LDFLAGS = $(GTK_LDFLAGS) -L../commonlib -lcommonlib $(X11_LIBS)
 
 OBJS = \
      nvpanel-gui.o \
