#!/bin/sh
#
# This is part 2 of the ppp-on script. It will perform the connection
# protocol for the desired connection.
#
#exec chat -v -f chat.script
rm /etc/ppp/chat.log
exec chat -r /etc/ppp/chat.log -f chat.script
